Import(Split("env PREFIX common bsdfsp client CLIENTS"))

if CLIENTS:
    fcatcmd=env.Program(target = 'fcatcmd',source=['fcatcmd.c']+client+common)
    fcdcmd=env.Program(target = 'fcdcmd', source=['fcdcmd.c','printpro.c']+client+common)
    fducmd=env.Program(target = 'fducmd', source=['fducmd.c']+client+common)
    ffindcmd=env.Program(target = 'ffindcmd',source=['ffindcmd.c']+client+common+bsdfsp)
    fget=env.StaticObject('fgetcmd.c', CPPDEFINES='-DCOMMAND_GET')
    fgetcmd=env.Program(target = 'fgetcmd',source=fget+client+common)
    fgrabcmd=env.Program(target = 'fgrabcmd',source=['fgrabcmd.c']+client+common)
    fhostcmd=env.Program(target = 'fhostcmd',source=['fhostcmd.c','fhost.c','fspprof.l'])
    flscmd=env.Program(target = 'flscmd',source=['flscmd.c']+client+common+bsdfsp)
    fmkdircmd=env.Program(target = 'fmkdir',source=['fmkdir.c']+client+common)
    fprocmd=env.Program(target = 'fprocmd',source=['fprocmd.c','printpro.c']+client+common)
    fputcmd=env.Program(target = 'fput',source=['fput.c']+client+common)
    frmcmd=env.Program(target = 'frmcmd',source=['frmcmd.c']+client+common)
    frmdircmd=env.Program(target = 'frmdircmd',source=['frmdircmd.c']+client+common)
    fvercmd=env.Program(target = 'fver',source=['fver.c']+client+common)
    fstatcmd=env.Program(target = 'fstatcmd',source=['fstatcmd.c']+client+common)
    fmvcmd=env.Program(target = 'fmvcmd',source=['fmvcmd.c']+client+common)
    fbyecmd=env.Program(target = 'fbye',source=['fbye.c']+client+common)
    fsetupcmd=env.Program(target = 'fsetupcmd',source=['fsetupcmd.c','fspsites.l','fhost.c']+client+common)

    PROGRAMS=[ fcatcmd, fcdcmd, fducmd, ffindcmd, fgetcmd, fgrabcmd, fhostcmd,
	     flscmd, fmkdircmd, fprocmd, fputcmd, frmcmd, frmdircmd, fvercmd,
	     fstatcmd, fmvcmd, fbyecmd, fsetupcmd ]

    for program in PROGRAMS:
	env.Install(dir = PREFIX+'/bin', source = program)
