Import(Split("env PREFIX DOCDIR SGML"))

env.Install(dir=DOCDIR,source=Split("PROTOCOL HISTORY faq.html"))
env.Alias("install",DOCDIR)
if SGML:
    env.Command('fsp-faq.html','fsp-faq.sgml','sgmlfmt -d docbook -f html fsp-faq.sgml',chdir=1)
    env.Install(dir=DOCDIR,source='fsp-faq.html')
