Import(Split("env PREFIX common bsdfsp SERVER"))

if SERVER:
  fspd=env.Program(target = 'fspd', source = Split('''
acl.c       file.c      main.c      random.c
conf.c      iprange.c   path.c      server.c
fifocache.c host.c      log.c       pidfile.c
''') + common  + bsdfsp)
  env.Install(dir = PREFIX+'/bin', source = fspd)
